export enum OrderStatus {
    PENDING = 'PENDING',
    PLACED = 'PLACED',
    IN_PROGRESS = 'IN_PROGRESS',
    PICKED = 'PICKED',
    CANCELED = 'CANCELED',
    DELAYED = 'DELAYED',
    DELIVERED = 'DELIVERED',
    PARTIALLY_DELIVERED = 'PARTIALLY_DELIVERED',
  }