export enum ProductCategory {
    Anklets = 'Anklets',
    Bangles = 'Bangles',
    Bracelets = 'Bracelets',
    Brooches = 'Brooches',
    Chain = 'Chain',
    Charms = 'Charms',
    Choker = 'Choker',
    Earrings = 'Earrings',
    Ghungroo = 'Ghungroo',
    Jewelry_Sets = 'Jewelry_Sets',
    Jhumkas = 'Jhumkas',
    Maang_Tikka = 'Maang_Tikka',
    Mangalsutra = 'Mangalsutra',
    Necklaces = 'Necklaces',
    Nose_Ring = 'Nose_Ring',
    Pendants = 'Pendants',
    Rings = 'Rings',
    Toe_Ring = 'Toe_Ring',
    Waist_Chains = 'Waist_Chains',
    Watches = 'Watches',
}